### ISSUE TITLE
dlopen failed: cannot locate symbol "atof" referenced by "libjsqlite.so"...

### ISSUE THREAD

**Issue by ahuarte47** [geopaparazzi/libjsqlite-spatialite-android#10]
Hi, I successly compiled the current version (4.2.1) in Windows7 x64 using NDK (r10 x64).
But when the library is loaded in android (System.loadLibrary("jsqlite");) I gets this error....

dlopen failed: cannot locate symbol "atof" referenced by "libjsqlite.so"...

Can you help me ?
Thanks!

Alvaro

**Comment by mj10777** [comment]
Sorry, I don't remember seeing this question before.

'atof' is a standard c function and therefore is used everywhere inside the many dependencies
* I would find it hard to believe that the NDK itself does not resolve this
   * i.e. add the needed code into the library

So, to be frank, I have no idea what the cause could be.

**Comment by ahuarte47** [comment]
Hi Mark, thanks for your reply. Sorry, I sincerely did not remember having this request open. Yesterday I closed it because of I solved the problem some time ago.

Best regards
Alvaro
