### ISSUE TITLE
Encrypt spatialite database

### ISSUE THREAD

**Issue by adolfdsilva** [geopaparazzi/libjsqlite-spatialite-android#11]
Hi,

I'm a newbie to android development and I'm currently using a spatialite lib given here: https://github.com/mrenouf/android-spatialite

What I want is to encrypt the spatialite database, but the problem I don't know where to start. 
I was thinking of using sqlcipher but, If I'am not wrong the sqlcipher replaces all the SQLiteDatabase instances, but how do i do this for spatialite.

Any ideas? Thanks!!!

**Comment by mj10777** [comment]
1) The project you are using is extremely old (Based on spatialite 2.3.1).
* you would not be able to support the present day geometries or database structures

2) I have no idea about encryption, nor do I understand the need
*  encrypting binary fields (such as geometries) is not a good idea

**Comment by adolfdsilva** [comment]
Thanks for the reply,My concern is not about the spatial data. It's about the user data and I have a single spatialite database.
That also stores user information.

I'll check how much effort is required for re-compiling spaitial source with additional tweaks. Else I'll need to have separate databases for user data and spatial data.

**Comment by adolfdsilva** [comment]
Well I ended up in separating the two databases. My sensitive non-spatial data i put in sqlite and the other tables for which i use spatial queries, I moved them to spatial database. 

It produced some data redundancy but well works for me.
