### ISSUE TITLE
Building libjsqlite-4.4.0-RC0 for Android from source

### ISSUE THREAD

**Issue by ddurgaprasad** [geopaparazzi/libjsqlite-spatialite-android#14]
I am trying the instructions to build android version using  http://www.gaia-gis.it/gaia-sins/libspatialite-4.4.0-RC0.tar.gz [1] . I am unable to get the things right per instructions provided at  https://code.google.com/archive/p/spatialite-android/ [2] .Looks like  the instructions are little bit outdated.Could you please share  latest  instructions to build the library for Android.I am looking for instructions on either linux or Windows/MingW.

Are these the dependencies sufficient to make us of 'VirtualKNN' ?
Proj4
GEOS
sqlite-amalgamation
libspatialite
jsqlite ( Is this suitable API for libspatialite-4.4.0-RC or does it require any updates?)
Another source of confusion in build instructions.

Should I use the instructions as in google code ? Why Make and Make install are not followed ?
`./configure --build=x86_64-pc-linux-gnu --host=arm-linux-eabi`

OR the instructions at http://www.gaia-gis.it/gaia-sins/mingw_how_to.html  ?

```
export "CFLAGS=-I/usr/local/include"
export "LDFLAGS=-L/usr/local/lib"
export "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig"
./configure --target=mingw32 --enable-rttopo=yes --enable-gcp=yes
make
make install-strip
```

**Comment by mj10777** [comment]
Your second link is very outdated and should not be used

Have a look here:

https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki

on that page, pre-compile libraries are offered that can be downloaded
- which may be all you need

The source code
 - javasqlite-20120209 (sqlite_jni.c,sqlite_jni.h)

is an adapted version that works with the present day spatialite/rasterlite2

This will soon be updated when spatialite 4.4.0 comes out
 - my local version has been adapted to work with 'rttopo'
