### ISSUE TITLE
How to check if jsqlite database is open ?

### ISSUE THREAD

**Issue by spapapan** [geopaparazzi/libjsqlite-spatialite-android#15]
I am trying to check if jsqlite is open or closed. For sqlite there is a method isOpen() that do the trick. Is there any similar method for jsqlite?

**Comment by mj10777** [comment]
As far as I can see (after a very quick search) no.

When we close the connections we set it to NULL
* other checks have not been needed

**Comment by spapapan** [comment]
So if you call the method close() you can check if the database is closed by checking if the database is null?
