### ISSUE TITLE
sqlite_jni.c needs to include <spatialite.h>

### ISSUE THREAD

**Issue by matspetter** [geopaparazzi/libjsqlite-spatialite-android#16]
sqlite_jni.c needs to include <spatialite.h> otherwise it doesn't compile/run properly when using
APP_ABI := x86_64

the reason is that sqlite_jni.c currently lacks the correct signature for spatialite_alloc_connection()
When not including spatialite.h then spatialite_alloc_connection() is undefined and becomes
int spatialite_alloc_connection()
by default. That works for 32 bit but NOT for 64 bit builds and it results in a crash.

**Comment by mj10777** [comment]
Indeed, you are quite right.

The following is needed:


#include <spatialite.h>
#ifdef HAVE_RASTERLITE2
#include "rasterlite2.h"
#endif


I am only now starting the needed adaptions for Spatialite 5.0, so it will take a while before it gets update here. Locally I have changed it.
Any other practical experience in 64 bit will be welcomed.

**Comment by mj10777** [comment]
No that I have started to build the project, the final needed correction is the following:

#include <spatialite_private.h>
#include <spatialite.h>
#if HAVE_RASTERLITE2 == 1
#include "rasterlite2.h"
#endif

**Comment by mj10777** [comment]
This should now be resolved.
