### ISSUE TITLE
Avoid being forced to run ./configure

### ISSUE THREAD

**Issue by matspetter** [geopaparazzi/libjsqlite-spatialite-android#17]
Would it be possible to check-in the results of your configure (and autoconf) runs into the repo? In that way it would be much easier to build the whole thing from sources.

If not, maybe have a master script on top level that runs configure for each needed sub-library with the correct parameters (== the parameters you are using).

**Comment by mj10777** [comment]
./configure is needed to create, for most projects, extra files that are not contained in the original archive of the project.

Also in some cases small adaptions need to be made.

Which './configure' command is used (when used at all) and the needed adaptions are placed in the corresponding .mk file

```c
# ./configure  --enable-rttopo --enable-gcp  --enable-examples=no --build=x86_64-pc-linux-gnu --host=arm-linux-eabi
...
# -------------------
# Excluded files:
...
# comment out TARGET_CPU in config.h - will be replaced with TARGET_ARCH_ABI
```
I will commit the present status (where Spatialite has been updated i.e. not rasterlite2) when the 3 build have run

armeabi-v7a arm64-v8a x86_64

**Comment by mj10777** [comment]
I have started a ***puch** of all the added/changed files (now at 8 of 4058)
* so this will take a while

By then the **[x86_64] Compile** should be completed
* ***armeabi-v7a*** and ***arm64-v8a*** are already finished

A summery of the Spatialite project can be seen here:
https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki/Android_4.5.0.mk

Either tonight or tomorrow I will upload the created libraries, and update the link (which now points to an older version)
