### ISSUE TITLE
VirtualRouting Version 5 support

### ISSUE THREAD

**Issue by am2222** [geopaparazzi/libjsqlite-spatialite-android#19]
Hi,
Does this port supports VirtualRouting Version 5?

https://www.gaia-gis.it/fossil/libspatialite/wiki?name=VirtualRouting

**Comment by mj10777** [comment]
Since it was only release last week: no

But it will when spatialite 5.0 is released

**Comment by mj10777** [comment]
At present it used Spatialite 5.0 development from around January.

**Comment by am2222** [comment]
@mj10777 thanks very much. I hope spatilite 5.0 releases soon

**Comment by mj10777** [comment]
Base on the present development code as of today (2018-05-08), including VirtualRouting 
- the following compiled libraries are available (using android-21):
-> armeabi-v7a  32-bit  
-> arm64-v8a     64-bit
-> x86_64          64-bit

For further details:

https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki/Android_5.0.0.mk

The archive with the compiled libraries can be downloaded with the following linux command:
 
wget https://raw.github.com/geopaparazzi/libjsqlite-spatialite-android/master/archive/20180508.libjsqlite.5.0.0.tar.bz2 

-----

**Comment by moovida** [comment]
Hi @mj10777 . We have delayed the release until Monday. Do you suggest to use these libraries for the release?

**Comment by mj10777** [comment]
Sorry, I heard no ring.

This must be tested first, I would say.

**Comment by mj10777** [comment]
The VirtualRouting portion may interest you for future versions.

https://www.gaia-gis.it/fossil/libspatialite/wiki?name=VirtualRouting

**Comment by moovida** [comment]
Thanks @mj10777 , then let's do this release with the old and then we start introducing this in the new version.

Routing will be very interesting indeed. 

One question aside: are you by any chance able to build spatialite also for IOS? We are investigating (very very slowly) a way to make a geopaparazzi for IOS and one sure limit for me would be the native lib for IOS.

**Comment by mj10777** [comment]
I have no experience with IOS at all.

**Comment by moovida** [comment]
I also do not :-) I was just wishing. No problem.

**Comment by mj10777** [comment]
@moovida : the following 2 things should be clarified
* dropping of **armeabi** : nobody reported machines that need it
* '**android-21** and min version: with 64 mandatory (August 2019, if I remember correctly)

**Comment by am2222** [comment]
@mj10777  I faced a problem, As I can not test queries using version 5 in GUI I tried this query

`SELECT DISTINCT vector_layers_statistics.table_name||';'||vector_layers_statistics.geometry_column||';'||vector_layers_statistics.layer_type||';ROWID;-1' AS vector_key,vector_layers.geometry_type||';'||vector_layers.coord_dimension||';'||vector_layers.srid||';'||vector_layers.spatial_index_enabled||';' AS vector_data,vector_layers_statistics.row_count||';'||vector_layers_statistics.extent_min_x||','||vector_layers_statistics.extent_min_y||','||vector_layers_statistics.extent_max_x||','||vector_layers_statistics.extent_max_y||';'||vector_layers_statistics.last_verified AS vector_extent FROM vector_layers_statistics INNER JOIN vector_layers ON vector_layers_statistics.table_name = vector_layers.table_name AND vector_layers_statistics.geometry_column = vector_layers.geometry_column WHERE (vector_layers.spatial_index_enabled = 1) AND (vector_layers_statistics.row_count IS NOT NULL) AND ((vector_layers_statistics.row_count = 0) OR ((vector_layers_statistics.extent_min_x IS NOT NULL) AND (vector_layers_statistics.extent_min_y IS NOT NULL) AND (vector_layers_statistics.extent_max_x IS NOT NULL) AND (vector_layers_statistics.extent_max_y IS NOT NULL))) ORDER BY vector_layers_statistics.layer_type DESC,vector_layers_statistics.table_name ASC,vector_layers_statistics.geometry_column ASC`

and it seems it does not return anything (I can run this query using Spatilite GUI and it works fine and returns two rows) but when I use the compiled version it returns no rows. could it be due to changes in new version?

I have got the query from geopaparazzi application

**Comment by mj10777** [comment]
Maybe there is nothing to display in that database.

An error message will be returned if there is a syntax error or missing tables.
' could it be due to changes in new version?'
* unlikely, since there are no Spatialite specific commands (only Spatialite specific tables)

**Comment by am2222** [comment]
@mj10777  I tried with this database.

https://www.gaia-gis.it/gaia-sins/routing-sample-5.0.0.7z

this is have at least two geometry tables. roads and houses but it returns no vectortables. Do I am missing sth? I have not tried the new version with other databases which was working with older versions of libspatilite

**Comment by am2222** [comment]
@mj10777 

When I run this query on sample/test DB (https://www.gaia-gis.it/gaia-sins/routing-sample-5.0.0.7z ) it returns this error. It seems it is sth internal. How can I debug it?

`select CreateRouting(  'roads_vw_data',  'roads_vw_bycar',  'roads_vw',  'node_from',  'node_to',  'geom',  NULL); `

`
05-15 09:08:18.201 26536-26536/spatilaitetest A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1 in tid 26536 (.spatilaitetest)`

**Comment by mj10777** [comment]
Please don't crosspost. You just asked the same question on the spatialite forum.
