### ISSUE TITLE
Missing files and directories

### ISSUE THREAD

**Issue by TFreudi1** [geopaparazzi/libjsqlite-spatialite-android#20]
I just downloaded (cloned) the current master branch and tried to compile it. I did'nt make complete list but files are missing like sqlite-3220000.mk, than I must change Android.mk (RASTERLITE2_PATH,RTTOPO_PATH ...) because the version that you put in there are not in the branch. 
I'm not through until now but is'nt there a complete path that I can compile ?
I need the  to recompile by my self because I din't found a prebuild arm64-v8a version of the lib.

**Comment by TFreudi1** [comment]
Sorry I'm so blind, there are the so-files that I need in the archive dir .
So my real problem is solved but still the question why the branch is not consistent.

**Comment by mj10777** [comment]
I have just uploaded the missing file sqlite-3220000.mk.
* other than comments there is no difference to sqlite-3170000.mk

There is a precompiled [you just saw this]
https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki/Android_5.0.0.mk

**Comment by mj10777** [comment]
Well, there are so many that sometimes the 'git add' is forgotten.

**Comment by TFreudi1** [comment]
Thats what I did, I maded a copy of sqlite-3170000.mk, but after that I got errors from Android.mk

librasterlite2-5.0.0 missing

 

Von: Mark Johnson [mailto:notifications@github.com] 
Gesendet: Mittwoch, 9. Mai 2018 14:31
An: geopaparazzi/libjsqlite-spatialite-android
Cc: TFreudi1; Author
Betreff: Re: [geopaparazzi/libjsqlite-spatialite-android] Missing files and directories (#20)

 

I have just uploaded the missing file sqlite-3220000.mk.

*	other than comments there is no difference to sqlite-3170000.mk

There is a precompiled [you just saw this]
https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki/Android_5.0.0.mk

**Comment by mj10777** [comment]
There is a 'Android_5.0.0.mk' for Spatialite and a 'Android_R5.0.0.mk' for Spatialite with Rasterlite2

Yes, you are right, it is now uploaded.

With 'git pull origin' everything should be updated.

**Comment by TFreudi1** [comment]
Great Thanks, next thing  … I did’nt have a “configure”, I’m on windows and use latest NDK (I guess it came Today J) and I just do a ndk-build.cmd

Now it misses

spatialite-android-library\jni\librttopo-20180125\headers\librttopo_geom.h

 

only the “configure” librttopo_geom.h.in is there.

 

But as I say I’m happy with the archive version, thank you for your really fast response, and for sharing and working on this project !

 

There is no urgent problem with it !

 

 

Von: Mark Johnson [mailto:notifications@github.com] 
Gesendet: Mittwoch, 9. Mai 2018 14:45
An: geopaparazzi/libjsqlite-spatialite-android
Cc: TFreudi1; Author
Betreff: Re: [geopaparazzi/libjsqlite-spatialite-android] Missing files and directories (#20)

 

There is a 'Android_5.0.0.mk' for Spatialite and a 'Android_R5.0.0.mk' for Spatialite with Rasterlite2

Yes, you are right, it is now uploaded.

With 'git pull origin' everything should be updated.

**Comment by imaatw** [comment]
Hi mj10777,

great thanks for you working this project,
it's missed librttopo_geom.h file and it in you gitingore list,
could you please upload it?

thanks a lot.

**Comment by mj10777** [comment]
removed librttopo_geom.h from gitignore and added file to project.
