### ISSUE TITLE
about build spatialite for android

### ISSUE THREAD

**Issue by aforme** [geopaparazzi/libjsqlite-spatialite-android#22]
hi , i want to build spatialite for android , but I have some problems when build

1. when i run **./autogen.sh**  then run  **./configure  --build=x86_64-pc-linux-gnu --host=arm-linux-eabi** in **librttopo-20180125** , i receive **configure : error : could not find geos-config within the current path...**
2. when i run **./configure  --enable-rttopo --enable-gcp  --enable-examples=no --build=x86_64-pc-linux-gnu --host=arm-linux-eabi** in **libspatialite-5.0.0** ,  i receive **configure : error : cannot find sqlite3.h ...**

so , do i need to copy these files to somewhere ? and do you have a script to batch configure ?

looking forward to your reply

**Comment by mj10777** [comment]
./configure has already been done in the copy on git (and the needed adaptions for config.h).
* it is indented to be used with the corresponding .mk file

**Comment by mj10777** [comment]
Well it is not an easy task.
The main goal of this project is to create the needed libraries for geopaparazzi.
* so everything in this git has already run

https://github.com/geopaparazzi/libjsqlite-spatialite-android/wiki/Android_5.0.0.mk

If you only need the libraries, they can be downloaded using the link in the above page.

**Comment by aforme** [comment]
thank you ! 
I'm using libjsqlite.so now , but jsqlite java wapper is not friendly , so i'm trying to use [https://github.com/requery/sqlite-android](url) ,and load spatialite extension .
