### ISSUE TITLE
missed librttopo_geom.h file

### ISSUE THREAD

**Issue by imaatw** [geopaparazzi/libjsqlite-spatialite-android#23]
Hi mj10777,

great thanks for you working on this project,
it's missed librttopo_geom.h file and it in your gitingore list,
could you please upload it?

thanks a lot.

**Comment by mj10777** [comment]
removed librttopo_geom.h from gitignore and added file to project.

Thank you for reporting.

**Comment by imaatw** [comment]
thank you very much
