### ISSUE TITLE
missing rttopo_config.h

### ISSUE THREAD

**Issue by imaatw** [geopaparazzi/libjsqlite-spatialite-android#24]
Hi, 

it's also missing rttopo_config.h file under /librttopo-20180125/src/ path (also in your gitignore list)
please help when you fell free
thank you~

**Comment by mj10777** [comment]
removed rttopo_config.h from gitignore and added file to project.

Lets hope that this the last, but should others turn up please inform
In normal C projects, these files are generated during the **configure**
* for this type of project is one of the **few exceptions** where they should be included

**Comment by imaatw** [comment]
great thanks for your reply !!
