### ISSUE TITLE
using LoadShapefile or ImportShapefile?

### ISSUE THREAD

**Issue by am2222** [geopaparazzi/libjsqlite-spatialite-android#25]
Hi,
is there any possiblility to use these functions in android port?
https://www.gaia-gis.it/spatialite-2.1/SpatiaLite-manual.html#t6a

**Comment by mj10777** [comment]
This port is based on spatialite 4.3 and soon for 5.0
* **do not use** older versions such as 2.1

http://www.gaia-gis.it/gaia-sins/spatialite-sql-latest.html

Basically all the commands should work, care must be taken when importing external files (such as ShapeFiles) that:
`export SPATIALITE_SECURITY=relaxed`

must be set.

Each function that needs this notes this in the above link.

An up-to-date cookbook, with many pratical samples, can be found here:

https://www.gaia-gis.it/gaia-sins/spatialite-cookbook-5/

**Comment by iceberg1369** [comment]
I tried to export shapefile using following command.
    
    SELECT ExportSHP(\"Point\",\"geometry\",\""+exportfile+"\",\"UTF-8\",\"POINT\");

and I tried to set env variable like this

     Os.setenv("SPATIALITE_SECURITY", "relaxed ", true);

but I could not export shape file.
